name: Deploy to EC2
on:
  push:
    branches: [ main ]      # main 브랜치에 push될 때만
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Copy repo & restart container on EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        # 필요하면 port: ${{ secrets.EC2_PORT }}
        script: |
          set -e
          if [ ! -d ~/soar-workflow ]; then
              git clone https://github.com/<YOUR_ID>/<YOUR_REPO>.git ~/soar-workflow
          fi
          cd ~/soar-workflow
          git pull

          cat > .env <<EOF
          SLACK_WEBHOOK=${{ secrets.SLACK_WEBHOOK }}
          CTI_API_KEY=${{ secrets.CTI_API_KEY }}
          CTI_PROVIDER=abuseipdb
          EOF

          docker compose down
          docker compose up --build -d

          echo "✅ Deploy Complete!"
